using System.Globalization;
using System.Text.Json;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace PoMiniGames.Features.PoGallery;

/// <summary>
/// PoGallery — dev-only demo surface for procedural Three.js models generated by
/// the img2threejs skill. See <see cref="PoGalleryEndpoints"/> for the manifest
/// endpoint and gating rationale.
///
/// Wire format:
///   GET  /api/diag/gallery → <see cref="GalleryManifest"/> (200) or 404 when disabled.
///   POST /api/gallery/upload → accept an image, store it, and return the refreshed
///        <see cref="GalleryManifest"/> (200) or 404 when disabled.
///
/// Pre-authored models are static ES modules under <c>wwwroot/games/pogallery/models/&lt;id&gt;/index.js</c>.
/// Uploaded images are stored under <c>wwwroot/games/pogallery/uploads/&lt;id&gt;/</c> and rendered
/// client-side by the viewer as an image-driven heightfield (see the viewer's
/// <c>?image=</c> mode). The Blazor page renders each model in an iframe pointing at
/// <c>/games/pogallery/viewer/?model=…&amp;title=…</c> or <c>/games/pogallery/viewer/?image=…&amp;title=…</c>.
/// </summary>
public static class PoGalleryEndpoints
{
    /// <summary>Max accepted upload size (5 MB) — generous for a reference photo, small
    /// enough to keep the static-file serving and the client-side heightfield sampling fast.</summary>
    internal const long MaxUploadBytes = 5 * 1024 * 1024;

    private static readonly string[] AllowedImageTypes = { "image/png", "image/jpeg", "image/webp" };

    /// <summary>
    /// Single source of truth for the static catalogue. <c>Kind</c> discriminates:
    ///   - <c>"model"</c>: a procedural Three.js module under
    ///     <c>wwwroot/games/pogallery/models/&lt;id&gt;/index.js</c>. The page renders it
    ///     as a viewer iframe via <see cref="GalleryModel.ViewerUrl"/>.
    ///   - <c>"preset"</c>: a reference image under
    ///     <c>wwwroot/games/pogallery/refs/&lt;id&gt;.&lt;ext&gt;</c>. The page renders
    ///     a small thumbnail + a click handler that submits the image through
    ///     <c>/api/gallery/upload</c> for instant heightfield feedback. The
    ///     <see cref="GalleryModel.ViewerUrl"/> still points at the existing viewer
    ///     so the static manifest is browsable.
    /// When a new procedural model is generated, add a <c>"model"</c> entry here and
    /// drop the module under <c>wwwroot/games/pogallery/models/&lt;id&gt;/index.js</c>.
    /// When a new reference image is curated, add a <c>"preset"</c> entry and drop the
    /// file under <c>wwwroot/games/pogallery/refs/&lt;id&gt;.&lt;ext&gt;</c>.
    /// </summary>
    internal static readonly IReadOnlyList<GalleryModel> Models = new[]
    {
        // Procedural model — the img2threejs 8-pass chair.
        new GalleryModel(
            Kind: "model",
            Id: "chair",
            Title: "Navy upholstered chair",
            Description: "Sled-frame chair with cantilever metal legs, single horizontal seam across the back, no arms. Reference image: wwwroot/games/pogallery/refs/chair.png. Generated by img2threejs strict pipeline.",
            ReferenceImage: "/games/pogallery/refs/chair.png",
            ModelUrl: "/games/pogallery/models/chair/index.js",
            ViewerUrl: "/games/pogallery/viewer/index.html?model=/games/pogallery/models/chair/index.js&title=Navy+upholstered+chair"),

        // Presets — curated reference images for testing the 2D→3D upload flow.
        // One click on a preset thumbnail POSTs the image to /api/gallery/upload
        // and the result appears as a heightfield card in the gallery.
        // The set covers the luminance and content-type space the heightfield sees:
        // stark monochrome (silhouette, apple), monochrome with geometric detail
        // (keyboard), photographic with high local contrast (pepperoni on black),
        // and photographic with low local contrast that needs the percentile-stretch
        // auto-contrast (margherita on white plate).
        new GalleryModel(
            Kind: "preset",
            Id: "silhouette-on-white",
            Title: "Silhouette (high contrast)",
            Description: "Stark black figure on white — the easiest possible case for the heightfield: full dynamic range, no auto-contrast needed.",
            ReferenceImage: "/games/pogallery/refs/silhouette-on-white.png",
            ModelUrl: "/games/pogallery/refs/silhouette-on-white.png",
            ViewerUrl: "/games/pogallery/viewer/index.html?image=%2Fgames%2Fpogallery%2Frefs%2Fsilhouette-on-white.png&title=Silhouette+%28high+contrast%29"),
        new GalleryModel(
            Kind: "preset",
            Id: "apple-logo",
            Title: "Apple logo (monochrome)",
            Description: "Public-domain Apple silhouette. Tests the heightfield on a non-human shape class.",
            ReferenceImage: "/games/pogallery/refs/apple-logo.png",
            ModelUrl: "/games/pogallery/refs/apple-logo.png",
            ViewerUrl: "/games/pogallery/viewer/index.html?image=%2Fgames%2Fpogallery%2Frefs%2Fapple-logo.png&title=Apple+logo"),
        new GalleryModel(
            Kind: "preset",
            Id: "keyboard",
            Title: "QWERTY keyboard (geometric)",
            Description: "Public-domain QWERTY keyboard diagram. Dense monochrome geometric detail — many small height features at different elevations.",
            ReferenceImage: "/games/pogallery/refs/keyboard.png",
            ModelUrl: "/games/pogallery/refs/keyboard.png",
            ViewerUrl: "/games/pogallery/viewer/index.html?image=%2Fgames%2Fpogallery%2Frefs%2Fkeyboard.png&title=QWERTY+keyboard"),
        new GalleryModel(
            Kind: "preset",
            Id: "pepperoni-pizza",
            Title: "Pepperoni pizza (photo)",
            Description: "Pepperoni pizza on a dark plate — high local contrast. The pepperoni discs read as small peaks against a darker floor.",
            ReferenceImage: "/games/pogallery/refs/pepperoni-pizza.jpg",
            ModelUrl: "/games/pogallery/refs/pepperoni-pizza.jpg",
            ViewerUrl: "/games/pogallery/viewer/index.html?image=%2Fgames%2Fpogallery%2Frefs%2Fpepperoni-pizza.jpg&title=Pepperoni+pizza"),
        new GalleryModel(
            Kind: "preset",
            Id: "pizza-margherita",
            Title: "Margherita pizza (low contrast)",
            Description: "Margherita on a white plate — narrow luminance range. Without the percentile-stretch auto-contrast the relief collapses to flat; with it, the basil and crust become legible.",
            ReferenceImage: "/games/pogallery/refs/pizza-margherita.jpg",
            ModelUrl: "/games/pogallery/refs/pizza-margherita.jpg",
            ViewerUrl: "/games/pogallery/viewer/index.html?image=%2Fgames%2Fpogallery%2Frefs%2Fpizza-margherita.jpg&title=Margherita+pizza"),
    };

    /// <summary>User-uploaded images, keyed by id. Backed by a JSON file on disk so the
    /// gallery survives API restarts — the upload directory is otherwise the only thing
    /// that persists, and the manifest needs to know what each upload represents (title,
    /// description, viewer URL). Without this, the <c>/uploads/&lt;id&gt;/source.png</c>
    /// file is still served but no gallery card points to it.</summary>
    private static readonly System.Collections.Concurrent.ConcurrentDictionary<string, GalleryModel> _uploads =
        new();

    /// <summary>Lazy seed flag — <see cref="EnsureManifestLoaded"/> is invoked on the
    /// first manifest build or upload so the static state is hydrated from disk on
    /// first use instead of needing an explicit startup hook (this is a static class,
    /// no DI).</summary>
    private static volatile bool _manifestLoaded;

    /// <summary>Serializes manifest writes so a crash mid-upload can't leave a
    /// half-written JSON file that the next process refuses to load.</summary>
    private static readonly object _writeLock = new();

    /// <summary>JSON serializer settings used for both load and save — kept here
    /// so the two paths can't drift out of sync (e.g. one writing indented, the
    /// other not).</summary>
    private static readonly JsonSerializerOptions _manifestJson = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    public static IEndpointRouteBuilder MapPoGalleryEndpoints(this IEndpointRouteBuilder app)
    {
        // Same gating pattern as /api/diag: FeatureFlags:EnableGallery defaults to
        // IsDevelopment() so the surface is unreachable in Production unless an
        // operator explicitly opts in. Returns 404 (not 403) when disabled to keep
        // the surface indistinguishable from "doesn't exist".
        app.MapGet("/api/diag/gallery", (IConfiguration cfg, IHostEnvironment env, IWebHostEnvironment webEnv) =>
        {
            if (!IsEnabled(cfg, env)) return Results.NotFound();

            var payload = BuildManifest(env, webEnv);
            return Results.Json(payload, statusCode: StatusCodes.Status200OK);
        }).RequireAuthorization();

        // RequiresAuthorization (signed-in only). The client's AntiforgeryHandler attaches
        // the X-CSRF-TOKEN header to all /api/* POSTs automatically, so the synchroniser
        // token is validated here — do not disable it.
        app.MapPost("/api/gallery/upload", UploadAsync)
            .RequireAuthorization();

        return app;
    }

    private static bool IsEnabled(IConfiguration cfg, IHostEnvironment env)
        => cfg.GetValue("FeatureFlags:EnableGallery", env.IsDevelopment());

    private static GalleryManifest BuildManifest(IHostEnvironment env, IWebHostEnvironment webEnv)
    {
        EnsureManifestLoaded(webEnv);
        return new GalleryManifest(
            GeneratedAt: DateTimeOffset.UtcNow.ToString("o", CultureInfo.InvariantCulture),
            Environment: env.EnvironmentName,
            Models: Models.Concat(_uploads.Values).ToArray());
    }

    /// <summary>Hydrate <see cref="_uploads"/> from disk on first use. Idempotent.
    /// Stale entries whose backing file is gone are dropped — the manifest file is
    /// rewritten so the cleanup is one-shot.</summary>
    private static void EnsureManifestLoaded(IWebHostEnvironment webEnv)
    {
        if (_manifestLoaded) return;
        lock (_writeLock)
        {
            if (_manifestLoaded) return;
            var path = ManifestPath(webEnv);
            if (path is not null && File.Exists(path))
            {
                try
                {
                    var json = File.ReadAllText(path);
                    var entries = JsonSerializer.Deserialize<List<GalleryModel>>(json, _manifestJson);
                    if (entries is not null)
                    {
                        foreach (var m in entries)
                        {
                            // Drop entries whose source file vanished — the gallery
                            // should never advertise a card that 404s on click.
                            var srcPath = webEnv.WebRootPath is null
                                ? null
                                : Path.Combine(webEnv.WebRootPath, m.ModelUrl.TrimStart('/').Replace('/', Path.DirectorySeparatorChar));
                            if (srcPath is not null && File.Exists(srcPath))
                                _uploads[m.Id] = m;
                        }
                    }
                }
                catch (Exception ex)
                {
                    // Don't crash the manifest endpoint because the JSON is malformed
                    // — log via the console and start fresh. The next upload rewrites
                    // the file from scratch.
                    Console.Error.WriteLine($"[PoGallery] Failed to load manifest at {path}: {ex.Message}");
                }
            }

            // Backfill: any <id>/ directory under uploads/ that has a source.<ext>
            // file but no manifest entry was uploaded before persistence shipped.
            // Decode real dimensions for the description so it doesn't read "0×0",
            // then write the manifest back so the backfill is one-shot.
            BackfillOrphans(webEnv);
            _manifestLoaded = true;
        }
    }

    /// <summary>Find upload directories with a source file but no manifest entry,
    /// synthesize a <see cref="GalleryModel"/> for each, and persist. Idempotent —
    /// running twice is a no-op because already-known ids are skipped.</summary>
    private static void BackfillOrphans(IWebHostEnvironment webEnv)
    {
        if (string.IsNullOrEmpty(webEnv.WebRootPath)) return;
        var uploadsDir = Path.Combine(webEnv.WebRootPath, "games", "pogallery", "uploads");
        if (!Directory.Exists(uploadsDir)) return;

        var manifestChanged = false;
        foreach (var dir in Directory.EnumerateDirectories(uploadsDir))
        {
            // Skip the manifest file itself if it ever appears as a sub-entry.
            var dirName = Path.GetFileName(dir);
            if (string.IsNullOrEmpty(dirName) || dirName.StartsWith('.')) continue;

            // Find the source file (any supported extension).
            string? sourceFile = null;
            string? ext = null;
            foreach (var candidate in Directory.EnumerateFiles(dir))
            {
                var name = Path.GetFileName(candidate);
                if (!name.StartsWith("source", StringComparison.OrdinalIgnoreCase)) continue;
                var candidateExt = Path.GetExtension(candidate).ToLowerInvariant();
                if (candidateExt is ".png" or ".jpg" or ".jpeg" or ".webp")
                {
                    sourceFile = candidate;
                    ext = candidateExt;
                    break;
                }
            }
            if (sourceFile is null) continue;

            // Build the id the upload endpoint would have used: "u-<8 hex>". The dir
            // name is the id; the seed list and live manifest already use the same
            // convention, so this matches.
            var id = dirName;
            if (_uploads.ContainsKey(id)) continue;

            // Decode dimensions from the file itself.
            int width = 0, height = 0;
            try
            {
                var bytes = File.ReadAllBytes(sourceFile);
                var dims = TryDecodeDimensions(bytes);
                width = dims.width;
                height = dims.height;
            }
            catch
            {
                // Leave dims at 0 — the description still renders, just with "0×0".
            }

            var contentType = ext switch
            {
                ".jpg" or ".jpeg" => "image/jpeg",
                ".webp" => "image/webp",
                _ => "image/png",
            };

            // Title: use the source filename minus its `source` prefix so a file
            // literally named "source.png" becomes the bare id, while a file the
            // user named before upload (rare here) keeps its name.
            var title = id; // dirs are u-XXXXXXXX, that's already a reasonable label
            var srcUrl = $"/games/pogallery/uploads/{id}/source{ext}";
            var model = new GalleryModel(
                Kind: "upload",
                Id: id,
                Title: title,
                Description: $"Uploaded image ({width}×{height}, {contentType}). Rendered by the PoGallery viewer as an image-driven heightfield: sampled luminance drives vertical displacement, sampled color drives vertex tint.",
                ReferenceImage: srcUrl,
                ModelUrl: srcUrl,
                ViewerUrl: $"/games/pogallery/viewer/index.html?image={Uri.EscapeDataString(srcUrl)}&title={Uri.EscapeDataString(title)}");

            _uploads[id] = model;
            manifestChanged = true;
        }

        if (manifestChanged)
        {
            Console.Error.WriteLine($"[PoGallery] Backfilled {_uploads.Count} upload(s) from disk on startup.");
            PersistManifest(webEnv);
        }
    }

    /// <summary>Pure-managed dimension decoder for PNG/JPEG/WebP. Accepts the full
    /// file bytes (not a stream) so it can be called from both the upload path
    /// and the backfill path that reads from disk.</summary>
    private static (int width, int height) TryDecodeDimensions(byte[] buf)
    {
        var read = buf.Length;
        if (read < 8) return (0, 0);

        // PNG: bytes 16..23 = IHDR width/height, big-endian.
        if (read >= 24 && buf[0] == 0x89 && buf[1] == 0x50 && buf[2] == 0x4E && buf[3] == 0x47
            && buf[12] == 'I' && buf[13] == 'H' && buf[14] == 'D' && buf[15] == 'R')
        {
            var w = (buf[16] << 24) | (buf[17] << 16) | (buf[18] << 8) | buf[19];
            var h = (buf[20] << 24) | (buf[21] << 16) | (buf[22] << 8) | buf[23];
            return (w, h);
        }

        // JPEG: scan for SOF0/SOF2.
        if (buf[0] == 0xFF && buf[1] == 0xD8)
        {
            var i = 2;
            while (i + 9 < read)
            {
                if (buf[i] != 0xFF) return (0, 0);
                while (i < read && buf[i] == 0xFF) i++;
                if (i >= read) break;
                var marker = buf[i++];
                if (marker == 0xD8 || marker == 0xD9 || (marker >= 0xD0 && marker <= 0xD7) || marker == 0x01)
                    continue;
                if (i + 2 > read) return (0, 0);
                var segLen = (buf[i] << 8) | buf[i + 1];
                if (marker == 0xC0 || marker == 0xC2)
                {
                    var h = (buf[i + 3] << 8) | buf[i + 4];
                    var w = (buf[i + 5] << 8) | buf[i + 6];
                    return (w, h);
                }
                i += segLen;
            }
            return (0, 0);
        }

        // WebP: see the inline comments in DecodeImageHeaderAsync for the fourcc rules.
        if (read >= 30 && buf[0] == 'R' && buf[1] == 'I' && buf[2] == 'F' && buf[3] == 'F'
            && buf[8] == 'W' && buf[9] == 'E' && buf[10] == 'B' && buf[11] == 'P')
        {
            var fourcc = System.Text.Encoding.ASCII.GetString(buf, 12, 4);
            if (fourcc == "VP8 " && read >= 30 && buf[23] == 0x9D && buf[24] == 0x01 && buf[25] == 0x2A)
            {
                var w = ((buf[26] | (buf[27] << 8)) & 0x3FFF);
                var h = ((buf[28] | (buf[29] << 8)) & 0x3FFF);
                return (w, h);
            }
            if (fourcc == "VP8L" && read >= 25)
            {
                var packed = buf[21] | (buf[22] << 8) | (buf[23] << 16) | (buf[24] << 24);
                var w = (packed & 0x3FFF) + 1;
                var h = ((packed >> 14) & 0x3FFF) + 1;
                return (w, h);
            }
            if (fourcc == "VP8X" && read >= 30)
            {
                var w = (buf[24] | (buf[25] << 8) | (buf[26] << 16)) + 1;
                var h = (buf[27] | (buf[28] << 8) | (buf[29] << 16)) + 1;
                return (w, h);
            }
        }

        return (0, 0);
    }

    /// <summary>Atomically rewrite the manifest after a successful upload. Write to a
    /// temp file then <see cref="File.Move(string,string,bool)"/> so a crash mid-write
    /// can't truncate the live manifest.</summary>
    private static void PersistManifest(IWebHostEnvironment webEnv)
    {
        var path = ManifestPath(webEnv);
        if (path is null) return;
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            var tmp = path + ".tmp";
            var json = JsonSerializer.Serialize(_uploads.Values.ToList(), _manifestJson);
            File.WriteAllText(tmp, json);
            // overwrite:true replaces the target atomically on Windows (rename-replace
            // semantics), so a reader never sees a half-written file.
            File.Move(tmp, path, overwrite: true);
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[PoGallery] Failed to persist manifest at {path}: {ex.Message}");
        }
    }

    /// <summary>Returns the on-disk path of the manifest file, or null if the web
    /// root isn't known yet (shouldn't happen in practice — every entry point that
    /// touches persistence also touches <see cref="IWebHostEnvironment"/>).</summary>
    private static string? ManifestPath(IWebHostEnvironment webEnv)
    {
        if (string.IsNullOrEmpty(webEnv.WebRootPath)) return null;
        return Path.Combine(webEnv.WebRootPath, "games", "pogallery", "uploads", ".manifest.json");
    }

    private static async Task<IResult> UploadAsync(
        HttpContext ctx,
        IConfiguration cfg,
        IHostEnvironment env,
        IWebHostEnvironment webEnv,
        CancellationToken ct)
    {
        if (!IsEnabled(cfg, env)) return Results.NotFound();

        if (!ctx.Request.HasFormContentType)
            return Results.BadRequest(new { error = "Expected multipart/form-data." });

        var form = await ctx.Request.ReadFormAsync(ct);
        var file = form.Files.GetFile("image");
        if (file is null || file.Length == 0)
            return Results.BadRequest(new { error = "No 'image' file in the request." });

        if (file.Length > MaxUploadBytes)
            return Results.BadRequest(new { error = $"Image exceeds {MaxUploadBytes / 1024 / 1024} MB limit." });

        var contentType = file.ContentType ?? "application/octet-stream";
        if (!AllowedImageTypes.Contains(contentType, StringComparer.OrdinalIgnoreCase))
            return Results.BadRequest(new { error = $"Unsupported content type '{contentType}'. Use PNG, JPEG, or WebP." });

        // Validate it decodes as an image rather than trusting the declared type.
        // Read the whole body once into a byte buffer — at 5 MB max this is cheap,
        // and it lets us extract real dimensions AND write to disk from the same
        // bytes without re-reading the IFormFile stream. Returns (format, w, h).
        byte[] bytes;
        await using (var ms = new MemoryStream())
        {
            await file.CopyToAsync(ms, ct);
            bytes = ms.ToArray();
        }
        var format = IdentifyFormat(bytes);
        if (format is null)
            return Results.BadRequest(new { error = "File is not a readable image." });
        var (width, height) = TryDecodeDimensions(bytes);

        var id = "u-" + Guid.NewGuid().ToString("N")[..8];
        var ext = ExtFor(contentType);
        var relative = Path.Combine("games", "pogallery", "uploads", id, $"source{ext}");
        var root = webEnv.WebRootPath
                   ?? throw new InvalidOperationException("WebRootPath is null; cannot persist uploads.");
        var absolute = Path.Combine(root, relative);
        Directory.CreateDirectory(Path.GetDirectoryName(absolute)!);

        await File.WriteAllBytesAsync(absolute, bytes, ct);

        var srcUrl = "/" + relative.Replace('\\', '/');
        var title = SanitizeTitle(file.FileName, id);
        var model = new GalleryModel(
            Kind: "upload",
            Id: id,
            Title: title,
            Description: $"Uploaded image ({width}×{height}, {contentType}). Rendered by the PoGallery viewer as an image-driven heightfield: sampled luminance drives vertical displacement, sampled color drives vertex tint.",
            ReferenceImage: srcUrl,
            ModelUrl: srcUrl,
            ViewerUrl: $"/games/pogallery/viewer/index.html?image={Uri.EscapeDataString(srcUrl)}&title={Uri.EscapeDataString(title)}");

        _uploads[id] = model;

        // Persist AFTER the in-memory dict is set so a write failure can't leave the
        // disk file ahead of the live state. The BuildManifest call below also forces
        // EnsureManifestLoaded (no-op after first call), keeping the load path hot.
        PersistManifest(webEnv);
        return Results.Json(BuildManifest(env, webEnv), statusCode: StatusCodes.Status201Created);
    }

    private static string SanitizeTitle(string fileName, string fallback)
    {
        var name = Path.GetFileNameWithoutExtension(fileName);
        name = string.Concat(name.Where(c => !char.IsControl(c) && c != '/' && c != '\\' && c != '?'));
        return string.IsNullOrWhiteSpace(name) ? fallback : name;
    }

    private static string ExtFor(string contentType)
        => contentType switch
        {
            "image/jpeg" => ".jpg",
            "image/webp" => ".webp",
            _ => ".png",
        };

    /// <summary>Identify the image format from a magic-bytes sniff. Returns "PNG",
    /// "JPEG", "WebP" or null. The same function backs both the upload validator
    /// and the backfill reader — single source of truth for "what is this file".</summary>
    private static string? IdentifyFormat(byte[] buf)
    {
        if (buf.Length < 8) return null;
        if (buf[0] == 0x89 && buf[1] == 0x50 && buf[2] == 0x4E && buf[3] == 0x47) return "PNG";
        if (buf[0] == 0xFF && buf[1] == 0xD8) return "JPEG";
        if (buf[0] == 'R' && buf[1] == 'I' && buf[2] == 'F' && buf[3] == 'F' &&
            buf.Length >= 12 && buf[8] == 'W' && buf[9] == 'E' && buf[10] == 'B' && buf[11] == 'P') return "WebP";
        return null;
    }
}

/// <summary>Wire-format DTO for <c>/api/diag/gallery</c>.</summary>
public sealed record GalleryManifest(
    string GeneratedAt,
    string Environment,
    IReadOnlyList<GalleryModel> Models);

/// <summary>One entry in the gallery. See <see cref="PoGalleryEndpoints.Models"/>.
/// <see cref="Kind"/> discriminates between static entries (<c>"model"</c> for
/// procedural Three.js modules, <c>"preset"</c> for clickable reference images)
/// and runtime entries (<c>"upload"</c> for images posted through
/// <c>/api/gallery/upload</c>). Defaults to <c>"model"</c> so older manifests
/// without the field still render — the page treats <c>"model"</c> and <c>"upload"</c>
/// as non-clickable and only renders <c>"preset"</c> as a clickable thumbnail.</summary>
public sealed record GalleryModel(
    string Id,
    string Title,
    string Description,
    string ReferenceImage,
    string ModelUrl,
    string ViewerUrl,
    string Kind = "model");
