#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Cross-tier coverage matrix for PoMiniGames. Extracts every [Fact]/[Theory]
  across the four test tiers, identifies the route(s) each test covers (by
  regex over the test body), and emits a Markdown table that flags (a) routes
  covered by more than one tier (redundancy) and (b) routes with no coverage
  (gaps).

.DESCRIPTION
  The 100/50/25/25 Rule only counts methods. The matrix adds the "where is this
  covered?" axis so the team can answer "is /api/infer covered twice?" in 30s
  instead of "felt by the team over a sprint".

.PARAMETER TierProject
  Optional root for a single tier (defaults to scanning all four).

.EXAMPLE
  pwsh scripts/coverage-matrix.ps1
  pwsh scripts/coverage-matrix.ps1 -TierProject tests/PoMiniGames.Unit
#>

[CmdletBinding()]
param(
    [string]$TierProject = ""
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

$tiers = [ordered]@{
    'Unit'        = 'tests/PoMiniGames.Unit'
    'Integration' = 'tests/PoMiniGames.Integration'
    'E2EAPI'      = 'tests/E2EAPI'
    'E2EUI'       = 'tests/E2EUI'
}

if ($TierProject) {
    $filtered = [ordered]@{}
    foreach ($k in $tiers.Keys) {
        if ($tiers[$k] -like "*$TierProject*") { $filtered[$k] = $tiers[$k] }
    }
    if ($filtered.Count -eq 0) {
        Write-Error "No tier matches '$TierProject'. Available: $($tiers.Values -join ', ')"
        exit 1
    }
    $tiers = $filtered
}

# Route extraction: find every quoted string that looks like a URL or a known
# pattern (/api/*, /health, /auth/*) and bucket the test by that surface.
$routePattern = [regex]'/(api|auth|health|openapi|scalar|diag|couplequiz|funquiz|poface|pojoker|poracer|posurvive|poclick|games|leaderboard|matchhistory|play)/[A-Za-z0-9_\-/{}\.:%?=]*'

function Get-RoutesFromFile {
    param([string]$Path)
    $content = Get-Content -Raw -LiteralPath $Path
    $matches = $routePattern.Matches($content)
    $routes = @()
    foreach ($m in $matches) {
        $r = $m.Value.TrimEnd(':,.')
        if ($r.Length -gt 2) { $routes += $r }
    }
    return ($routes | Sort-Object -Unique)
}

Write-Host "`n=== Coverage Matrix ===`n" -ForegroundColor Cyan
$matrix = @{}
$totalByTier = @{}

foreach ($tier in $tiers.Keys) {
    $proj = $tiers[$tier]
    Write-Host "Scanning $tier ($proj)..." -ForegroundColor Gray
    $files = Get-ChildItem -Path $proj -Filter '*.cs' -Recurse |
             Where-Object { $_.FullName -notmatch '\\(bin|obj)\\' }

    $tests = @()
    foreach ($f in $files) {
        $content = Get-Content -Raw -LiteralPath $f.FullName
        $factLines = [regex]::Matches($content, '\[(Fact|Theory)[^\]]*\]')
        foreach ($match in $factLines) {
            # Walk forward to the next '(' to capture the method signature.
            $startIdx = $match.Index + $match.Length
            $next = $content.IndexOf('(', $startIdx)
            if ($next -lt 0) { continue }
            $paren = 1
            $i = $next + 1
            while ($i -lt $content.Length -and $paren -gt 0) {
                if ($content[$i] -eq '(') { $paren++ }
                elseif ($content[$i] -eq ')') { $paren-- }
                $i++
            }
            $signature = $content.Substring($next + 1, $i - $next - 2).Trim()
            $methodName = ($signature -split '\(')[0].Trim()
            $tests += [pscustomobject]@{
                File     = $f.Name
                Method   = $methodName
                Routes   = Get-RoutesFromFile -Path $f.FullName
            }
        }
    }
    $totalByTier[$tier] = $tests.Count

    foreach ($t in $tests) {
        foreach ($r in $t.Routes) {
            if (-not $matrix.ContainsKey($r)) { $matrix[$r] = @{ Unit = $false; Integration = $false; E2EAPI = $false; E2EUI = $false; Count = 0 } }
            $matrix[$r][$tier] = $true
            $matrix[$r].Count++
        }
    }
}

# Emit Markdown table.
$mdPath = Join-Path $repoRoot 'docs/qa-coverage-matrix.md'
$md = New-Object System.Text.StringBuilder
[void]$md.AppendLine('# PoMiniGames — Cross-Tier Coverage Matrix')
[void]$md.AppendLine()
[void]$md.AppendLine('Auto-generated by `scripts/coverage-matrix.ps1`. The "Tiers" column lists which tiers cover the route; multi-tier entries are flagged as redundancy.')
[void]$md.AppendLine()
[void]$md.AppendLine('## Per-tier totals')
[void]$md.AppendLine()
[void]$md.AppendLine('| Tier | Tests | Ceiling |')
[void]$md.AppendLine('|---|---|---|')
$ceiling = @{ 'Unit' = 100; 'Integration' = 50; 'E2EAPI' = 25; 'E2EUI' = 25 }
foreach ($tier in $tiers.Keys) {
    [void]$md.AppendLine(('| {0} | {1} | {2} |' -f $tier, $totalByTier[$tier], $ceiling[$tier]))
}

[void]$md.AppendLine()
[void]$md.AppendLine('## Routes by coverage')
[void]$md.AppendLine()
[void]$md.AppendLine('| Route | Unit | Integration | E2EAPI | E2EUI | Tiers |')
[void]$md.AppendLine('|---|---|---|---|---|---|')
foreach ($r in ($matrix.Keys | Sort-Object)) {
    $row = $matrix[$r]
    $tiersCovered = @()
    foreach ($t in @('Unit','Integration','E2EAPI','E2EUI')) {
        if ($row[$t]) { $tiersCovered += $t }
    }
    $tierList = if ($tiersCovered.Count -gt 0) { $tiersCovered -join ', ' } else { '—' }
    $flag = if ($tiersCovered.Count -gt 1) { '⚠️' } elseif ($tiersCovered.Count -eq 1) { '✅' } else { '❌' }
    [void]$md.AppendLine(('| `{0}` | {1} | {2} | {3} | {4} | {5} {6} |' -f $r,
        $(if ($row['Unit'])        { '✓' } else { '' }),
        $(if ($row['Integration']) { '✓' } else { '' }),
        $(if ($row['E2EAPI'])      { '✓' } else { '' }),
        $(if ($row['E2EUI'])       { '✓' } else { '' }),
        $tierList,
        $flag))
}

[void]$md.AppendLine()
[void]$md.AppendLine('## Legend')
[void]$md.AppendLine()
[void]$md.AppendLine('- ⚠️  Covered by > 1 tier — review for redundancy; consolidate or relocate to the cheapest tier.')
[void]$md.AppendLine('- ✅  Covered by exactly 1 tier.')
[void]$md.AppendLine('- ❌  No tier currently covers this route — gap; add a test.')

$mdDir = Split-Path $mdPath
if (-not (Test-Path $mdDir)) { New-Item -ItemType Directory -Path $mdDir -Force | Out-Null }
Set-Content -LiteralPath $mdPath -Value $md.ToString()

Write-Host "Matrix written to: $mdPath" -ForegroundColor Green
Write-Host "Routes discovered: $($matrix.Keys.Count)" -ForegroundColor Gray
Write-Host "Multi-tier routes (review for redundancy): $((($matrix.Values | Where-Object { $_.Count -gt 1 }).Count))" -ForegroundColor Yellow
Write-Host "Uncovered routes (gaps): $((($matrix.Values | Where-Object { $_.Count -eq 0 }).Count))" -ForegroundColor Red